const PERMISSIONS = require('./permissions');

module.exports = {
  // 🔐 Full Access
  superadmin: Object.values(PERMISSIONS),

  // 🛒 Store Staff
  admin: [
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,

    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.READ_CATEGORY,
    PERMISSIONS.UPDATE_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,

    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.READ_ORDER,

    PERMISSIONS.CREATE_STOCK,
    PERMISSIONS.READ_STOCK,
    PERMISSIONS.UPDATE_STOCK,

    PERMISSIONS.READ_USER,

    PERMISSIONS.READ_TRANSACTION,
    PERMISSIONS.CREATE_TRANSACTION,

    PERMISSIONS.READ_SYSTEM,
    PERMISSIONS.UPDATE_SYSTEM,

    PERMISSIONS.READ_DISCOUNT,
    PERMISSIONS.CREATE_DISCOUNT,
    PERMISSIONS.UPDATE_DISCOUNT,

    PERMISSIONS.READ_FAVORITE,
    PERMISSIONS.CREATE_FAVORITE,  
    PERMISSIONS.DELETE_FAVORITE,

    PERMISSIONS.READ_RATING,
    PERMISSIONS.CREATE_RATING,

    PERMISSIONS.READ_CART,
    PERMISSIONS.CREATE_CART,
    PERMISSIONS.UPDATE_CART,
    PERMISSIONS.DELETE_CART,

    PERMISSIONS.READ_DELIVERY,
    PERMISSIONS.UPDATE_DELIVERY,

    PERMISSIONS.READ_TRANSACTION,
    PERMISSIONS.CREATE_TRANSACTION,

    PERMISSIONS.READ_SYMBOL,
    PERMISSIONS.CREATE_SYMBOL,
    PERMISSIONS.UPDATE_SYMBOL,
    PERMISSIONS.DELETE_SYMBOL,


    PERMISSIONS.READ_CURRENCY,
    PERMISSIONS.CREATE_CURRENCY,
    PERMISSIONS.UPDATE_CURRENCY,  
    PERMISSIONS.DELETE_CURRENCY,

    PERMISSIONS.CREATE_CUSTOMER_FEEDBACK,
    PERMISSIONS.READ_CUSTOMER_FEEDBACK,
    PERMISSIONS.UPDATE_CUSTOMER_FEEDBACK,
    PERMISSIONS.DELETE_CUSTOMER_FEEDBACK,

    PERMISSIONS.CREATE_PROMOTION,
    PERMISSIONS.READ_PROMOTION,
    PERMISSIONS.UPDATE_PROMOTION,
    PERMISSIONS.DELETE_PROMOTION,





  ],

  // 🚚 Delivery Staff
  delivery: [
    PERMISSIONS.READ_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.READ_DELIVERY,
    PERMISSIONS.UPDATE_DELIVERY
  ],

  // 🧍 Customer
  customer: [
    PERMISSIONS.CREATE_FAVORITE,
    PERMISSIONS.READ_FAVORITE,
    PERMISSIONS.DELETE_FAVORITE,

    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.READ_CATEGORY,

    PERMISSIONS.CREATE_RATING,
    PERMISSIONS.READ_RATING,

    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.READ_ORDER,

    PERMISSIONS.CREATE_CART,
    PERMISSIONS.READ_CART,
    PERMISSIONS.UPDATE_CART,
    PERMISSIONS.DELETE_CART,

    
    PERMISSIONS.READ_TRANSACTION,
    PERMISSIONS.CREATE_TRANSACTION,

    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.UPDATE_STOCK,  // Add stock update permission
    PERMISSIONS.READ_STOCK,    // Add stock read permission

    PERMISSIONS.CREATE_CUSTOMER_FEEDBACK,
    PERMISSIONS.READ_CUSTOMER_FEEDBACK,
    PERMISSIONS.UPDATE_CUSTOMER_FEEDBACK,
    PERMISSIONS.DELETE_CUSTOMER_FEEDBACK,

    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,

    PERMISSIONS.READ_SYMBOL,
    
    PERMISSIONS.READ_PROMOTION,

    PERMISSIONS.READ_CURRENCY,
    PERMISSIONS.UPDATE_USER,

  ]
};
